spring:
  application:
    name: ms-cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    defaultZone:
      register-with-eureka: http://localhost8761/eureka
